replicaCount: 1
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
logstashPipeline:
  logstash.conf: |
    input { beats { port => 5044 } }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }
